### ISSUE TITLE
Ore isnt regenerating

### ISSUE THREAD

**Issue by TypicalShavonne** [xHexed/Oregen3#37]
`[02:47:09 WARN]: [Oregen3] Plugin Oregen3 v1.6.2 generated an exception while executing task 8563
java.lang.IllegalStateException: Asynchronous block remove!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Purpur-"4ff0630"]
        at net.minecraft.world.level.block.state.BlockBehaviour.onRemove(BlockBehaviour.java:145) ~[app:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:913) ~[app:?]
        at net.minecraft.world.level.chunk.LevelChunk.setType(LevelChunk.java:708) ~[app:?]
        at net.minecraft.world.level.Level.setBlock(Level.java:733) ~[app:?]
        at net.minecraft.world.level.Level.setBlock(Level.java:695) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:198) ~[patched_1.17.1.jar:git-Purpur-"4ff0630"]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setBlockData(CraftBlock.java:182) ~[patched_1.17.1.jar:git-Purpur-"4ff0630"]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setType(CraftBlock.java:171) ~[patched_1.17.1.jar:git-Purpur-"4ff0630"]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setType(CraftBlock.java:165) ~[patched_1.17.1.jar:git-Purpur-"4ff0630"]
        at me.banbeucmas.oregen3.handler.block.placer.VanillaBlockPlacer.placeBlock(VanillaBlockPlacer.java:15) ~[Oregen3-1.6.2.jar:?]
        at me.banbeucmas.oregen3.handler.block.placetask.NormalBlockPlaceTask.placeBlock(NormalBlockPlaceTask.java:9) ~[Oregen3-1.6.2.jar:?]
        at me.banbeucmas.oregen3.handler.event.BlockEventHandler.generate(BlockEventHandler.java:17) ~[Oregen3-1.6.2.jar:?]
        at me.banbeucmas.oregen3.handler.event.AsyncBlockEventHandler.lambda$generateBlock$0(AsyncBlockEventHandler.java:18) ~[Oregen3-1.6.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-"4ff0630"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-"4ff0630"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-"4ff0630"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]`
       
 version: This server is running Purpur version git-Purpur-"4ff0630" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4ff0630 on ver/1.17.1)
 
 Ore isnt regenerating when i broke it, and the console spam this error
 Plugin version: https://github.com/xHexed/Oregen3/actions/runs/1573250995

**Comment by Khanh1402** [comment]
You can fix it by disable global.listener.asyncListener.I think this is the fault of the author, he used BukkitAPI in Async

**Comment by TypicalShavonne** [comment]
> You can fix it by disable global.listener.asyncListener. I think this is the fault of the author, he used BukkitAPI in Async

i have turned it off but still the same

**Comment by Khanh1402** [comment]
> > You can fix it by disable global.listener.asyncListener. I think this is the fault of the author, he used BukkitAPI in Async
> 
> i have turned it off but still the same

You must restart your server not reload plugin.

**Comment by xHexed** [comment]
Maybe fixed. (Actually i fixed this right when you reported but forgot to commit :skull:)
